[package]
name = "delharc"
version = "0.8.0"
authors = ["Rafal Michalski <royaltm75@gmail.com>"]
edition = "2024"
description = "A library for parsing and extracting files from LHA/LZH archives."
categories = ["compression"]
keywords = ["LHA", "LZH", "UNLHA"]
homepage = "https://github.com/royaltm/rust-delharc"
repository = "https://github.com/royaltm/rust-delharc"
license = "MIT OR Apache-2.0"
readme = "README.md"
exclude = [".github", ".gitignore", "tests/*", "examples/*"]
rust-version = "1.95"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["std", "lh1", "lz", "pm"]
std = ["chrono/std", "chrono/clock"]
# -lh1- decompression
lh1 = []
# -lhx- decompression
lhx = []
# -lzs- and -lz5- decompression
lz = []
# -pm1- and -pm2- decompression
pm = []
# Expose internal utilities - enables LHAv2 decoder customization.
extend = []
# Enable HuffTree::build_tree_with_sort and it becomes default tree building method.
# Adds ~8-15kB (depending on optimization level) bytes to code size.
# Only slightly impacts performance on LHAv2 decoding - an increase of ~1%-4%.
fast-tree-build = []
# Remove assertions that eliminate boundary checks in critical functions.
# This only affects code if debug_assertions are not enabled.
# Enabling this feature reduces performance by ~10-50% or more.
no-unsafe-assertions = []

[dependencies]
chrono = { version = "0.4", default-features = false }
bitflags = "2.13"
memchr = { version = "2", default-features = false }
bytemuck = { version = "1.25", features = ["derive", "min_const_generics", "extern_crate_alloc", "align_offset"] }

[dev-dependencies]
crc-any = { version = "3", default-features = false }
criterion = { version = "0.8", features = ["html_reports"] }
gofer = { version = "0.2", default-features = false, features = ["std", "http", "https"] }
rand = "0.10.2"

[[bench]]
name = "statictree"
harness = false
required-features = ["std", "extend", "fast-tree-build"]

[[bench]]
name = "lhav2"
harness = false
required-features = ["std", "lhx"]

[[bench]]
name = "aminet"
harness = false
required-features = ["std"]

[[bench]]
name = "pmarc"
harness = false
required-features = ["std", "pm"]

[workspace]
members = [
  ".",
  "examples/embedded"
]

[profile.release]
opt-level = 3
lto = true
incremental = false
codegen-units = 1
